//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int IdTicket { get; set; }
        public string Code_of_Ticket { get; set; }
        public int FlightTypesId { get; set; }
        public int SchedulesId { get; set; }
        public int AirplanePilotsId { get; set; }
        public int CitiesId { get; set; }
    
        public virtual AirplanePilot AirplanePilot { get; set; }
        public virtual City City { get; set; }
        public virtual FlightType FlightType { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
